---
- name: List Passbolt users
  command: "docker-compose exec -T {{ passbolt_tenant }}_app mysql -sN \
    -h {{ passbolt_database_host }} \
    -u {{ passbolt_database_user }} \
    -p{{ passbolt_database_password }} \
    -e 'use {{ passbolt_database_name }};SELECT username FROM users;'"
  args:
    chdir: "{{ passbolt_tenant_dir }}"
  changed_when: no
  register: list_users_result

- name: "Create Passbolt admin user {{ passbolt_admin_username }}"
  command: "docker-compose exec -T {{ passbolt_tenant }}_app su -m -c '/var/www/passbolt/bin/cake \
             passbolt register_user \
             -u {{ passbolt_admin_username }} \
             -f {{ passbolt_admin_first_name }} \
             -l {{ passbolt_admin_last_name }} \
             -r admin' -s /bin/sh www-data"
  args:
    chdir: "{{ passbolt_tenant_dir }}"
  changed_when: no
  register: create_admin_user_result
  when: passbolt_admin_username not in list_users_result.stdout
