---
- name: Create base config dir
  file:
    path: "{{ passbolt_base_dir }}"
    mode: "0755"
    owner: "{{ passbolt_user }}"
    group: "{{ passbolt_group }}"
    state: directory

- name: Create tenant config dir
  file:
    path: "{{ passbolt_tenant_dir }}"
    mode: "0755"
    owner: "{{ passbolt_user }}"
    group: "{{ passbolt_group }}"
    state: directory

- name: Create tenant .env file
  template:
    src: .env.j2
    dest: "{{ passbolt_tenant_dir }}/.env"
    mode: "0660"
    owner: "{{ passbolt_user }}"
    group: "{{ passbolt_group }}"
  notify: "Restart {{ passbolt_tenant }} Passbolt"

- name: Create tenant database.env file
  template:
    src: database.env.j2
    dest: "{{ passbolt_tenant_dir }}/database.env"
    mode: "0660"
    owner: "{{ passbolt_user }}"
    group: "{{ passbolt_group }}"
  notify: "Restart {{ passbolt_tenant }} Passbolt"

- name: Create tenant app.env file
  template:
    src: app.env.j2
    dest: "{{ passbolt_tenant_dir }}/app.env"
    mode: "0660"
    owner: "{{ passbolt_user }}"
    group: "{{ passbolt_group }}"
  notify: "Restart {{ passbolt_tenant }} Passbolt"

- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ passbolt_tenant_dir }}/docker-compose.yml"
    mode: "0644"
    owner: "{{ passbolt_user }}"
    group: "{{ passbolt_group }}"
  notify: "Restart {{ passbolt_tenant }} Passbolt"
