---
driver:
  name: hetznercloud
lint: |
  set -e
  yamllint .
platforms:
  - name: ${MOLECULE_TEST_SCOPE:-default}-1
    server_type: cx11
    image: ${MOLECULE_PLATFORM:-debian-10}
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        passbolt_email_transport_default_port: 3465
        passbolt_email_transport_default_user: admin
        passbolt_email_transport_default_domain: passbolt.local
        passbolt_email_transport_default_ssl: yes
        passbolt_email_transport_default_username: "{{ passbolt_email_transport_default_user }}@{{ passbolt_email_transport_default_domain }}"
        passbolt_email_transport_default_password: secret
        passbolt_email_transport_default_host: 127.0.0.1
        passbolt_admin_username: admin@passbolt.local
        passbolt_admin_first_name: Average
        passbolt_admin_last_name: Joe
  lint: |
    set -e
    ansible-lint
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
