---
driver:
  name: hetznercloud
lint: |
  set -e
  yamllint .
platforms:
  - name: ${MOLECULE_TEST_SCOPE:-default}-1
    server_type: cx11
    image: ${MOLECULE_PLATFORM:-debian-10}
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3.7
    host_vars:
      "${MOLECULE_TEST_SCOPE:-default}-1":
        vlan_ip: 172.0.0.2
  lint: |
    set -e
    ansible-lint
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
