---
- name: Install base OS packages
  hosts: all
  tasks:
    - name: Install setuptools
      package:
        name: python3-setuptools
        state: present

- name: Install role dependencies
  hosts: all
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
      - name: docker-compose
    docker_install_compose: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
