---
- name: Install base OS packages
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install setuptools
      package:
        name: python3-setuptools
        state: present

- name: Install role dependencies
  hosts: all
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
      - name: docker-compose
    docker_install_compose: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- name: Prepare service dependencies
  hosts: all
  tasks:
    - name: Run GreenMail test mail server
      docker_container:
        name: mail_server_1
        image: greenmail/standalone:1.6.0
        env:
          GREENMAIL_OPTS: "-Dgreenmail.setup.test.all \
          -Dgreenmail.hostname=0.0.0.0 \
          -Dgreenmail.defaultHostname={{ passbolt_email_transport_default_domain }} \
          -Dgreenmail.verbose \
          -Dgreenmail.users={{ passbolt_email_transport_default_username }}:{{ passbolt_email_transport_default_password }}@{{ passbolt_email_transport_default_domain }}"
        published_ports:
          - 127.0.0.1:3465:3465
