version: '3.4'
services:
  database:
    image: "${PASSBOLT_DATABASE_IMAGE}"
    env_file:
      - database.env
    volumes:
      - database:/var/lib/mysql
    ports:
      - "${PASSBOLT_DATABASE_BIND_ADDRESS}:${PASSBOLT_DATABASE_PORT}:3306"
    restart: unless-stopped
  app:
    image: "${PASSBOLT_IMAGE}"
    tty: true
    depends_on:
      - database
    env_file:
      - app.env
    command: ["/usr/bin/wait-for.sh", "-t", "0", "database:3306", "--", "/docker-entrypoint.sh"]
    volumes:
      - "app-gpg:/var/www/passbolt/config/gpg"
      - "app-images:/var/www/passbolt/webroot/img/public"
      - /dev/urandom:/dev/random
    tmpfs:
      - /run
    ports:
      - "${PASSBOLT_HTTP_BIND_ADDRESS}:${PASSBOLT_HTTP_PORT}:80"
      - "${PASSBOLT_HTTPS_BIND_ADDRESS}:${PASSBOLT_HTTPS_PORT}:443"
    restart: unless-stopped
volumes:
  app-gpg:
  app-images:
  database:
